ALTER DATABASE [FTOM] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FTOM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FTOM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FTOM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FTOM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FTOM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FTOM] SET ARITHABORT OFF 
GO

ALTER DATABASE [FTOM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FTOM] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FTOM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FTOM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FTOM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FTOM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FTOM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FTOM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FTOM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FTOM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FTOM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FTOM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FTOM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FTOM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FTOM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FTOM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FTOM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FTOM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FTOM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FTOM] SET  MULTI_USER 
GO

ALTER DATABASE [FTOM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FTOM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FTOM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FTOM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FTOM] SET  READ_WRITE 
GO